### ISSUE TITLE
length of video in embed will occasionally leave out zeros in the tens place of the minutes (i.e. 2:06 -> 2:6) [small issue]

### ISSUE THREAD

**Issue by njdetwiler** [Headline/musicbot-issues#4]
title. embed will display the length of a video as being only two digits if the tens place of the minutes is a zero. this may also apply to the minutes or hours place but i was unable to easily find a suitable video to test. examples in image links below. 
3:02
![3:02](https://user-images.githubusercontent.com/14206091/141722816-6efbf6e7-910a-4872-adc0-42fb6fbdaaf9.png)
3:01
![3:01](https://user-images.githubusercontent.com/14206091/141722869-b5f9da80-d317-47fd-8f4e-dca718131e5e.png)
4:03
![4:03](https://user-images.githubusercontent.com/14206091/141722881-ce983cd8-51e1-40cf-b76a-21e5683649dc.png)

**Comment by Headline** [comment]
Fixed! Thanks
